"""
Django settings for dilipadsite project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

###from __future__ import absolute_import, unicode_literals

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

from django.utils.translation import ugettext_lazy as _

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

with open('/etc/secret_key.txt') as f:
    SECRET_KEY = f.read().strip()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost']

SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = (
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'dilipadsite',
    'downtime',
    'django_contactme',
    'home',
    'static_sitemaps',
    'data',
    'search',
    'full',
    'members',
    'help',
    'widget_tweaks',
    'haystack',
    'andablog',
    'taggit',
    'markitup',
    'mptt',
    'taggit_templatetags',
    
)


MIDDLEWARE_CLASSES = (
    'downtime.middleware.DowntimeMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'dilipadsite.exception_logging_middleware.ExceptionLoggingMiddleware',
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
    
)

ROOT_URLCONF = 'dilipadsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "django.core.context_processors.request",
                'django.template.context_processors.i18n',
                'dilipadsite.context_processors.getvars',
                'django.contrib.auth.context_processors.auth',
                
            ],
        },
    },
]


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    },
    'cache_machine': {
        'BACKEND': 'diskcache.DjangoCache',
        'LOCATION': '/home/lipad/django_cache',
        'SHARDS': 4,
        'DATABASE_TIMEOUT': 10.0,
        'OPTIONS': {
            'size_limit': 2 ** 33,  # 8 gigabytes
            'eviction_policy':u'least-frequently-used'
        },
    },
}

CACHE_MIDDLEWARE_ALIAS = "default"
CACHE_MIDDLEWARE_SECONDS = 300

WSGI_APPLICATION = 'dilipadsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'lipad_dilipadsite',
        'USER': 'user',
        'PASSWORD': 'pw',
        'HOST': '0.0.0.0',
        'PORT': '5432',
        'CONN_MAX_AGE':300,
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

DATE_FORMAT = "Y-m-d"

USE_L10N = False

USE_TZ = True

MARKITUP_FILTER = ('markdown.markdown', {'safe_mode': False})
MARKITUP_SET = 'markitup/sets/markdown'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATIC_ROOT = "/home/lipad/static/"
MEDIA_ROOT = "/home/lipad/media/"

# App Settings

INTERNAL_IPS = ('0.0.0.0')

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.solr_backend.SolrEngine',
        'URL': 'http://0.0.0.0:8080/solr'
    },
}

GRAPPELLI_ADMIN_TITLE = 'Lipad Admin'
ENDLESS_PAGINATION_DEFAULT_CALLABLE_ARROWS = True
ENDLESS_PAGINATION_DEFAULT_CALLABLE_EXTREMES = 2
ENDLESS_PAGINATION_PER_PAGE = 15
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

DOWNTIME_EXEMPT_PATHS = (
    '/admin',
)

# STATICSITEMAPS_ROOT_SITEMAP = 'dilipadsite.sitemaps.sitemaps'

SITE_ID = 5

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'user@gmail.com'
DEFAULT_FROM_EMAIL = 'user@gmail.com'
SERVER_EMAIL ='user@gmail.com'

with open('/etc/email_password.txt') as f:
    emailpw = f.read().strip()

EMAIL_HOST_PASSWORD = emailpw
EMAIL_PORT = 587

ADMINS = (('Lipad Admin', 'user@gmail.com'),)

CONTACTME_NOTIFY_TO = "Lipad Admin <user@gmail.com>>"
CONTACTME_SALT = ""
CONTACTME_MSG_MAX_LEN = 3000

STATICSITEMAPS_ROOT_SITEMAP = 'dilipadsite.urls.sitemaps'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'standard': {
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s'
        },
    },
    'handlers': {
        'default': {
            'level':'WARNING',
            'class':'logging.FileHandler',
            'filename': '/var/log/lipad/lipad-django.log',
            'formatter':'standard',
        },  
        'request_handler': {
                'level':'WARNING',
                'class':'logging.FileHandler',
                'filename': '/var/log/lipad/lipad-django.log',
                'formatter':'standard',
        },
    },
    'loggers': {

        '': {
            'handlers': ['default'],
            'level': 'WARNING',
            'propagate': True
        },
        'django.request': {
            'handlers': ['request_handler'],
            'level': 'WARNING',
            'propagate': False
        },
    }
}
